### ISSUE TITLE
God I love simple solutions 

### ISSUE THREAD

**Issue by su77ungr** [tomtreffke/PiHole-on-K3s#1]
Honestly you saved me a ton of time. Danke dir **!**

**Comment by tomtreffke** [comment]
Happy to help! Did it work out for you or did you step because of my comments? 🤨😃

**Comment by su77ungr** [comment]
Your .yml manifest should be linked in the documentation of the pihole docker image. There was no reference on how to set the env variables so this was very helpful.

**Comment by tomtreffke** [comment]
Thanks mate. Really happy, if you got any improvements in your pihole k3s journey, let me know. :)
